name: GameMaker Windows Build CI (Bscotch)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Find YYP file
        id: find_yyp
        run: |
          $yyp = Get-ChildItem -Path "${{ github.workspace }}" -Recurse -Filter *.yyp | Select-Object -First 1
          if (-not $yyp) {
            Write-Error "❌ No .yyp file found!"
            exit 1
          }
          echo "YYP file: $($yyp.FullName)"
          echo "yyp-path=$($yyp.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Setup Igor CLI (via Bscotch)
        uses: bscotch/igor-setup@v2
        id: igor
        with:
          target-yyp: ${{ steps.find_yyp.outputs.yyp-path }}
          access-key: ${{ secrets.ACCESS_KEY }}

      - name: Build Game (via Bscotch)
        uses: bscotch/igor-build@v1
        id: build
        with:
          yyp-path: ${{ steps.find_yyp.outputs.yyp-path }}
          user-dir: ${{ steps.igor.outputs.user-dir }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ${{ steps.build.outputs.out-dir }}
