name: Continuous Integration for Windows export

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: windows-2022

    steps:
      # ✅ Step 1: Checkout the repository (with LFS)
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # ✅ Step 2: Find the .yyp file automatically
      - id: find_yyp
        name: 🔍 Find the .yyp file
        shell: pwsh
        run: |
          $yyp = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter *.yyp | Select-Object -First 1
          if (-not $yyp) {
            Write-Error "❌ No .yyp file found!"
            exit 1
          }
          "yyp-path=$($yyp.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "✅ Found YYP at $($yyp.FullName)"

      # ✅ Step 3: Set up Igor using Access Key only
      - name: 🧰 Setup Igor with Access Key
        uses: bscotch/igor-setup@v2
        id: igor
        with:
          access-key: ${{ secrets.ACCESS_KEY }}
          gm-version: stable  # Optional: you can specify version like 2024.5.0.10

      # ✅ Step 4: Build the game
      - name: 🛠️ Build Game Project (Windows)
        uses: bscotch/igor-build@v1
        id: build
        with:
          yyp-path: ${{ steps.find_yyp.outputs.yyp-path }}
          user-dir: ${{ steps.igor.outputs.user-dir }}
          output-dir: build
          runtime: Windows

      # ✅ Step 5: Upload the build artifacts
      - name: ⬆️ Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: igor-build-windows
          path: ${{ steps.build.outputs.out-dir }}
          retention-days: 1
