name: Continuous Integration for GX.Game Export
on: 
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: windows-2022
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4
        with:
          lfs: true

      # Find the .yyp file
      - id: find_yyp
        name: Find the yyp file
        run: |
          $yyp = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter *.yyp | Select-Object -First 1
          Write-Output "YYP file found at: $yyp"
          "yyp-path=$($yyp.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      # Setup Igor (CLI tool for GameMaker)
      - name: use Igor Setup
        uses: bscotch/igor-setup@v1
        id: igor
        with:
          target-yyp: ${{ steps.find_yyp.outputs.yyp-path }}
          access-key: ${{ secrets.ACCESS_KEY }}

      # Run the build for Windows (GX.Game target)
      - name: use Igor build (GX.Game)
        uses: bscotch/igor-build@v1
        id: build
        with:
          yyp-path: ${{ steps.find_yyp.outputs.yyp-path }}
          user-dir: ${{ steps.igor.outputs.user-dir }}
          target: Windows
          output: gx

      # Upload the GX.Game build output
      - name: upload GX.Game build
        uses: actions/upload-artifact@v4
        with:
          name: gxgame-build-windows
          path: ${{ steps.build.outputs.out-dir }}
          retention-days: 1
